package jml.util;
import jml.basics.Algorithm;
import jml.basics.Result;
import jml.basics.Tracer;

/**
 * <p>Title: SingleResultTracer</p>
 * <p>Description: Structure to manage a result object.</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: Universidad Nacional de Colombia</p>
 * @author Jonatan Gomez
 * @version 1.0
 */
public class SingleResultTracer implements Tracer {
 /**
  * Results generated by the iterative algorithm iteration by iteration
  */
  private Result result = null;

  /**
   * Creates a new SingleResultTracer
   */
  public SingleResultTracer() { }
  
  /**
   * Adds a new object
   * @param alg Algorithm
   * @param obj The object to add
   */
  public void add(Algorithm alg, Object obj) {
    result = (Result) obj;
  }
  
  /**
   * Return the result of the experiment
   * @return result of the experiment
   */
  public Result getStat() { return result; }


}
