function data=importFile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 09-Apr-2012 16:54:25

DELIMITER = '\t';
HEADERLINES = 8;

% Import the file
data = importdata(fileToRead1, DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
vars = fieldnames(data);
for i = 1:length(vars)
    assignin('base', vars{i}, data.(vars{i}));
end

