function plotK(Data1,Data2,Data3)
z1 = size(Data1.data,2);
z2 = size(Data2.data,2);
z3 = size(Data3.data,2);
t1 = Data1.data(:,1);
t2 = Data2.data(:,1);
t3 = Data3.data(:,1);
k1 = Data1.data(:,z1);
k2 = Data2.data(:,z2);
k3 = Data3.data(:,z3);
tau1 = k1 .* (Data1.data(:,3) + 0.3) + 2 .* sqrt(k1) .* Data1.data(:,5);
tau2 = k2 .* (Data2.data(:,3) + 0.3) + 2 .* sqrt(k2) .* Data2.data(:,5);
tau3 = k3 .* (Data3.data(:,3) + 0.3) + 2 .* sqrt(k3) .* Data3.data(:,5);
itau1 = cumtrapz(t1,tau1.^2);
itau2 = cumtrapz(t2,tau2.^2);
itau3 = cumtrapz(t3,tau3.^2);
figure;
plot(t1,k1,'g--',t2,k2,'r-',t3,k3,'k-');
legend('SF','OSM','SMNF');
xlabel('t');
title('k_{phi} values.');
figure;
plot(t1,tau1,'g--',t2,tau2,'r-',t3,tau3,'k-');
legend('SF','OSM','SMNF');
xlabel('t');
title('tau_{phi} values.');
figure;
plot(t1,itau1,'g--',t2,itau2,'r-',t3,itau3,'k-');
legend('SF','OSM','SMNF');
xlabel('t');
title('Integral of square tau_{phi} values.');